class ResourceAlreadyExists(Exception):
    pass


class ResourceNotFound(Exception):
    pass
